### ISSUE TITLE
"buttons_map" variable incorrectly named

### ISSUE THREAD

**Issue by NotThatRqd** [NotThatRqd/btnify#2]
In the bind_server function in lib.rs, "buttons_map" is incorrectly named and should be "button_handlers" to reflect its type

**Comment by gaurab-khanal** [comment]
Can I work on this?

**Comment by NotThatRqd** [comment]
Sure, just leave a pull request with the changes :)

**Comment by NotThatRqd** [comment]
fixed in commit 6f8f431
